/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ColorRouteImport } from './routes/color'
import { Route as PlayRouteImport } from './routes/play'
import { Route as SuggestRouteImport } from './routes/suggest'
import { Route as TopRouteImport } from './routes/top'
import { Route as SquishyIdRouteImport } from './routes/squishy/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorRoute = ColorRouteImport.update({
  id: '/color',
  path: '/color',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const SuggestRoute = SuggestRouteImport.update({
  id: '/suggest',
  path: '/suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const TopRoute = TopRouteImport.update({
  id: '/top',
  path: '/top',
  getParentRoute: () => rootRouteImport,
} as any)
const SquishyIdRoute = SquishyIdRouteImport.update({
  id: '/squishy/$id',
  path: '/squishy/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/color': typeof ColorRoute
  '/play': typeof PlayRoute
  '/suggest': typeof SuggestRoute
  '/top': typeof TopRoute
  '/squishy/$id': typeof SquishyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/color': typeof ColorRoute
  '/play': typeof PlayRoute
  '/suggest': typeof SuggestRoute
  '/top': typeof TopRoute
  '/squishy/$id': typeof SquishyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/color': typeof ColorRoute
  '/play': typeof PlayRoute
  '/suggest': typeof SuggestRoute
  '/top': typeof TopRoute
  '/squishy/$id': typeof SquishyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/color' | '/play' | '/suggest' | '/top' | '/squishy/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/color' | '/play' | '/suggest' | '/top' | '/squishy/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/color'
    | '/play'
    | '/suggest'
    | '/top'
    | '/squishy/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ColorRoute: typeof ColorRoute
  PlayRoute: typeof PlayRoute
  SuggestRoute: typeof SuggestRoute
  TopRoute: typeof TopRoute
  SquishyIdRoute: typeof SquishyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color': {
      id: '/color'
      path: '/color'
      fullPath: '/color'
      preLoaderRoute: typeof ColorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggest': {
      id: '/suggest'
      path: '/suggest'
      fullPath: '/suggest'
      preLoaderRoute: typeof SuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top': {
      id: '/top'
      path: '/top'
      fullPath: '/top'
      preLoaderRoute: typeof TopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squishy/$id': {
      id: '/squishy/$id'
      path: '/squishy/$id'
      fullPath: '/squishy/$id'
      preLoaderRoute: typeof SquishyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ColorRoute: ColorRoute,
  PlayRoute: PlayRoute,
  SuggestRoute: SuggestRoute,
  TopRoute: TopRoute,
  SquishyIdRoute: SquishyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
